// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_Yd5qpNv4WQAgNK6QXVOOc_FZl_hbqs',
    appId: '1:657429260211:web:81288dd2358fa47aba0dc6',
    messagingSenderId: '657429260211',
    projectId: 'hcie-yous-935a1',
    authDomain: 'hcie-yous-935a1.firebaseapp.com',
    storageBucket: 'hcie-yous-935a1.appspot.com',
    measurementId: 'G-GRRY9BF8B0',
    databaseURL: 'https://capstone-uniq-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0coacLwnxkwH7IBKcAEtvjymG14OWeM',
    appId: '1:657429260211:android:ac1c03408436ce51ba0dc6',
    messagingSenderId: '657429260211',
    projectId: 'hcie-yous-935a1',
    storageBucket: 'hcie-yous-935a1.appspot.com',
    databaseURL: 'https://capstone-uniq-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkHDfvi9yWq2g7KEElI2mPauBktOuLWGk',
    appId: '1:657429260211:ios:9c493ed22e47646aba0dc6',
    messagingSenderId: '657429260211',
    projectId: 'hcie-yous-935a1',
    storageBucket: 'hcie-yous-935a1.appspot.com',
    iosClientId: '657429260211-kjm01nhvumabbfau3mc1kdl2f9vke0ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.yous',
    databaseURL: 'https://capstone-uniq-default-rtdb.firebaseio.com',
  );
}
