// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7y_gO5HcCk1Pl5yrW-WUW8iDTPiX6KGY',
    appId: '1:649232623400:web:9d81a82bf46fa1e49d121d',
    messagingSenderId: '649232623400',
    projectId: 'capstone-uniq',
    authDomain: 'capstone-uniq.firebaseapp.com',
    storageBucket: 'capstone-uniq.appspot.com',
    measurementId: 'G-FVVFKHMVZP',
    databaseURL: 'https://capstone-uniq-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Lj45cNhtoQKUH3Dc0dPcwG_55-q8as8',
    appId: '1:649232623400:android:eb41468cb3bc0b3c9d121d',
    messagingSenderId: '649232623400',
    projectId: 'capstone-uniq',
    storageBucket: 'capstone-uniq.appspot.com',
    databaseURL: 'https://capstone-uniq-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsyzyncpC4F6TeRXuiS7SurBiIwzMnQwo',
    appId: '1:649232623400:ios:89461b45f6b1217c9d121d',
    messagingSenderId: '649232623400',
    projectId: 'capstone-uniq',
    storageBucket: 'capstone-uniq.appspot.com',
    iosClientId: '649232623400-lanvdvs0mdjtok2q5p1an5e7ejmari0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.handongHanBakwi',
  );
}
